### ISSUE TITLE
BLAS : Bad memory unallocation! crash and warnings.

### ISSUE THREAD

**Issue by palango** [staticfloat/homebrew-julia#194] opened 2015-12-05 20:46 UTC
Crosspost from juliaLang/julia#14263. The dmg binary on the website works, the homebrew version shows the following:

I just played around and got these strange errors. When I make the matrix 100x100, everything works fine. 500x500 crashes and 1000x1000 prints errors but returns output.
I'm on OS X 10.11.1 with julia 0.4.1 from staticfloats homebrew repo.

```
julia> svd(rand(500, 500));
BLAS : Bad memory unallocation! :    4  0x7fff52821340

signal (11): Segmentation fault: 11
dgemv_ at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
dlabrd_ at /usr/local/opt/openblas-julia/lib/libopenblas.dylib (unknown line)
[1]    88975 segmentation fault  julia
```
```
○ % julia                                                                                  20:16:26
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.1 (2015-11-08 10:33 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin15.0.0

julia> svd(rand(1000, 1000));
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed41c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed42c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed43c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
BLAS : Bad memory unallocation! :    4  0x7fff59ed44c0
```

**Comment by staticfloat** [comment] 2015-12-11 04:33
Hmmm, very strange.  I can do `svd(rand(1000, 1000))` just fine on my OSX 10.11.2 laptop, using both the 0.4.1 and recently released 0.4.2 bottles.  What processor type is in your machine?  (Find out via `versioninfo()`):

```
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34* (2015-12-06 21:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by palango** [comment] 2015-12-13 15:31
Updated to 0.4.2 an still see the same behaviour. 500x500 crashes and 1000x1000 outputs warnings.
```
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34* (2015-12-06 21:47 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by staticfloat** [comment] 2015-12-14 20:02
@xianyi do you have any idea what is going on here?

**Comment by matthieugomez** [comment] 2016-01-30 14:06
Same issue here.

**Comment by xianyi** [comment] 2016-02-26 17:15
Could you try OpenBLAS 0.2.16.rc1 version? I cannot reproduce this issue yet.

**Comment by matthieugomez** [comment] 2016-03-06 18:54
Could you walk me through updating OpenBLAS?

**Comment by matthieugomez** [comment] 2016-03-06 18:58
I'm not sure if this is related but even in the dmg version of Julia, the folllowing command stops Julia
```julia
svdfact(rand(177, 750))
```
while these work
```julia
svdfact(rand(176, 750))
svdfact(rand(178, 750))
```

**Comment by xianyi** [comment] 2016-03-07 02:02
@matthieugomez , I think this bug should be fixed in latest release.

**Comment by matthieugomez** [comment] 2016-03-07 02:03
Thanks. So I downloaded the source, runned make, but I'm not sure what to
do next

**Comment by matthieugomez** [comment] 2016-03-30 12:06
So there is a new release of OpenBlas 0.2.17. I'm not sure how to install it with Julia to check there are no more problems.

**Comment by staticfloat** [comment] 2016-03-30 23:54
@matthieugomez are you trying to test with a `julia` that you built from source, or with a `julia` from Homebrew?

**Comment by matthieugomez** [comment] 2016-03-31 13:37
The thing I'm not sure about is how to make Julia use the newest version of OpenBlas 0.2.17. If I follow the instructions in the README, I can only get to the 0.2.15 version
```
brew install openblas-julia --HEAD        
#Warning: staticfloat/julia/openblas-julia-0.2.15 already installed
```
Are you going to update the homebrew-julia for the new version of Julia and OpenBlas? Maybe I should test again then.

**Comment by staticfloat** [comment] 2016-04-04 03:52
We have updated to `v0.2.17`, please `brew update` and see if the problem persists.

**Comment by matthieugomez** [comment] 2016-04-07 20:15
The two issues are solved with the new update. Thanks a lot!

**Closed** 2016-06-24 09:23 UTC
